# Generated by Django 5.0.1 on 2024-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='video',
        ),
        migrations.AddField(
            model_name='stories',
            name='link',
            field=models.URLField(default='https://www.youtube.com/embed/default_video_id'),
        ),
    ]
