# Generated by Django 5.0.1 on 2024-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_stories_video_stories_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listening',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='name',
        ),
        migrations.RemoveField(
            model_name='speaking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='writing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zoom',
            name='image',
        ),
        migrations.RemoveField(
            model_name='zoom',
            name='link',
        ),
        migrations.RemoveField(
            model_name='zoom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zoom',
            name='time',
        ),
        migrations.AddField(
            model_name='zoom',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listening',
            name='link',
            field=models.URLField(default='https://www.youtube.com/embed/default_video_id'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='link',
            field=models.URLField(default='https://www.youtube.com/embed/default_video_id'),
        ),
        migrations.AlterField(
            model_name='speaking',
            name='link',
            field=models.URLField(default='https://www.youtube.com/embed/default_video_id'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='link',
            field=models.URLField(default='https://www.youtube.com/embed/default_video_id'),
        ),
    ]
