# Generated by Django 5.0.1 on 2024-01-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_listening_name_remove_reading_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoom',
            name='url',
        ),
    ]
